---
- name: "Update HAProxy and converge configuration"
  hosts: "all"
  vars:
    state: "update"
    iac_blueprint:
      haproxy:
        frontends:
          - name: "web"
            bind: "127.0.0.1"
            port: 8080
            default_backend: "apps"
        backends:
          - name: "apps"
            servers:
              - name: "app6"
                address: "2001:db8::1"
                port: 9001
  roles:
    - role: "ansible-iac-role-haproxy"
